# Generated by Django 5.1.6 on 2026-04-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_following_userprofile_count_following_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='count_followers',
        ),
    ]
