# Generated by Django 5.1.6 on 2026-04-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_followers_userprofile_count_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='count_followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='count_following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_posts',
        ),
    ]
