# Generated by Django 5.1.6 on 2026-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_userprofile_count_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_profile',
            field=models.ImageField(blank=True, null=True, upload_to='display_profile/'),
        ),
    ]
